import { CourseModuleData } from './types';

export const COURSE_MODULES: CourseModuleData[] = [
  {
    id: 'waves',
    status: 'Premium',
    icon: '🌊',
    title: 'Propagation Speed & Acoustic Variables',
    description: 'Explore how sound travels through different media. Understand the key acoustic variables and the factors that determine propagation speed in this foundational lesson.',
    features: ['Longitudinal wave simulation', 'Interactive acoustic variables', 'Kinetic speed deviation matrix'],
    hasWaveAnimation: true,
  },
  {
    id: 'transducers',
    status: 'Premium',
    icon: '⚡',
    title: 'Fundamentals of Ultrasound Transducers',
    description: 'A deep dive into exploring Transducers & Transducer Components. Learn about the piezoelectric effect, component trade-offs, frequency selection, and bandwidth.',
    features: ['Piezoelectric Energy Conversion', 'Backing Material Resolution Lab', 'Resonance Frequency Selection'],
  },
  {
    id: 'resolution',
    status: 'Interactive',
    icon: '🔍',
    title: 'Axial & Lateral Resolution',
    description: 'Understand resolution concepts through precise beam width demonstrations and target separation exercises.',
    features: ['LARRD vs LATA Visualization', 'Dynamic Focal Point Control', 'Slice Thickness Depth Analysis'],
  },
  {
    id: 'pulsed',
    status: 'Advanced',
    icon: '📡',
    title: 'Pulsed Wave Operation',
    description: 'Master pulse-echo cycles with dynamic timing diagrams and PRF calculations through interactive scenarios.',
    features: ['Range Equation Chronometer', 'PRP/PRF Timing Interface', 'Duty Factor Duty Cycle HUD'],
  },
   {
    id: 'doppler',
    status: 'Premium',
    icon: '🎯',
    title: 'Doppler Physics & Imaging Modes',
    description: 'Master the Doppler effect, from the core equation to a full breakdown of CW, PW, Color, and Power Doppler modes in clinical practice.',
    features: [
        'Vector Analysis & Parabolic Flow',
        'Spectral Doppler Caliper Lab',
        'Color Steering & Angle Correction'
    ],
  },
  {
    id: 'knobology',
    status: 'Practical',
    icon: '🎛️',
    title: 'System Optimization (Knobology)',
    description: 'A hands-on simulator to master the art of image optimization. Learn what each knob does and how to combine them to get the perfect image in any clinical scenario.',
    features: ['Interactive Control Panel', 'Master Signal-to-Noise Ratio', 'Optimization Console Feedback'],
  },
   {
    id: 'artifacts',
    status: 'Premium',
    icon: '🎨',
    title: 'Common Imaging Artifacts',
    description: 'Learn to identify and understand the most common imaging artifacts. This lesson focuses on Reverberation, Shadowing, and Enhancement.',
    features: ['Interactive Reverberation Logic', 'Attenuation Artifact Mapping', 'Corrective Maneuver Training'],
  },
    {
    id: 'advanced_artifacts',
    status: 'Premium',
    icon: '🌌',
    title: 'Advanced Artifacts',
    description: 'Go beyond the basics to identify and understand more complex artifacts like Mirror Image, Side/Grating Lobes, and Speed Error artifacts.',
    features: ['Mirror Image Ray-Tracing', 'Side Lobe Energy Maps', 'Speed Error Misregistration Lab'],
  },
  {
    id: 'harmonics',
    status: 'Premium',
    icon: '🎵',
    title: 'Harmonic Imaging',
    description: 'Learn how nonlinear wave propagation creates harmonic frequencies and how this is used to dramatically improve image quality by reducing artifacts.',
    features: [
      'Nonlinear Propagation Waveforms',
      'Harmonic Advantage Comparison',
      'Spectrum Analysis HUD'
    ],
  },
  {
    id: 'elastography',
    status: 'Advanced',
    icon: '🧱',
    title: 'Advanced Mode: Elastography',
    description: 'Go beyond grayscale and learn how to image tissue stiffness. This module covers the physics of strain and shear wave elastography and their clinical applications.',
    features: ['Strain vs. Shear Wave Simulation', 'ARFI Pulse Kinetic Tracking', 'Liver Fibrosis Staging Matrix'],
  },
  {
    id: 'contrast_agents',
    status: 'Advanced',
    icon: '✨',
    title: 'Contrast Agents & Microbubbles',
    description: 'Explore the physics of microbubble contrast agents. Learn how they enhance signals, respond to acoustic pressure, and enable advanced imaging techniques.',
    features: ['Harmonic Bubble Resonance', 'Microbubble Disruption Lab', 'Clinical Phase Simulation'],
  },
  {
    id: '3d_4d',
    status: 'Advanced',
    icon: '🧊',
    title: '3D/4D Imaging',
    description: 'Explore the technology behind creating three-dimensional volumes and real-time 4D imaging. Understand data acquisition, volume rendering, and clinical applications.',
    features: ['3D Volumetric Ray-Casting', 'MPR Orthogonal Slicing', 'Real-Time 4D Rendering'],
  },
  {
    id: 'hemodynamics',
    status: 'Clinical',
    icon: '❤️',
    title: 'Hemodynamics',
    description: 'Study blood flow dynamics with beautiful fluid simulations and vessel compliance demonstrations.',
    features: ['Laminar vs Turbulent Dynamics', 'Bernoulli Pressure Calculus', 'Poiseuille’s Flow Lab'],
  },
  {
    id: 'safety',
    status: 'Premium',
    icon: '🛡️',
    title: 'Bioeffects and Safety',
    description: 'A hands-on simulator for understanding ALARA, TI, and MI. Learn to manage patient safety in real-time with an interactive control panel and clinical scenarios.',
    features: ['Cavitation Threshold Lab', 'Thermal Absorption Simulation', 'SPTA Intensity HUD'],
  },
  {
    id: 'biomedical_physics',
    status: 'Premium',
    icon: '🔬',
    title: 'Biomedical Physics & Bio-instrumentation',
    description: 'A deeper look at the fundamental interactions between ultrasound and biological tissues, including advanced concepts in attenuation, scattering, and impedance.',
    features: ['Rayleigh Scattering Kinetic Lab', 'Tissue Impedance Mismatch Lab', 'Signal Chain Architecture'],
  },
  {
    id: 'abdominal',
    status: 'Clinical',
    icon: '🏥',
    title: 'Clinical Application: Abdominal',
    description: 'Apply your physics knowledge to abdominal scanning. This module covers key protocols, anatomy, and common measurements like the Renal Resistive Index (RI).',
    features: ['Anatomy Mapping Protocol', 'Pathology Detection Training', 'Renal RI Calculation Lab'],
  },
  {
    id: 'cardiac',
    status: 'Clinical',
    icon: '🫀',
    title: 'Clinical Application: Cardiac',
    description: 'An introduction to echocardiography, covering cardiac anatomy, standard imaging windows, and fundamental measurements like Ejection Fraction.',
    features: ['M-Mode Motion Analysis', 'Pulsatile Cardiac Rhythms'],
  },
  {
    id: 'vascular',
    status: 'Clinical',
    icon: '🩸',
    title: 'Clinical Application: Vascular',
    description: 'Master the basics of vascular ultrasound, from carotid stenosis grading to venous insufficiency testing.',
    features: ['Carotid Stenosis Pulse Lab', 'DVT Compression Maneuver', 'Ankle-Brachial Index (ABI)'],
  },
  {
    id: 'msk',
    status: 'Clinical',
    icon: '💪',
    title: 'Clinical Application: MSK',
    description: 'Explore the dynamic world of Musculoskeletal (MSK) ultrasound. Learn about the critical concept of anisotropy, tendon pathology, and dynamic imaging techniques.',
    features: ['Anisotropy Angular Physics', 'Tendon Pathology Simulation', 'Dynamic Joint Tracking'],
  },
  {
    id: 'clinical_case_simulator',
    status: 'New!',
    icon: '🧑‍⚕️',
    title: 'AI Clinical Case Simulator',
    description: 'Apply your physics knowledge in a real-world diagnostic challenge. Interact with an AI-powered patient case, generate ultrasound images, and make a diagnosis.',
    features: ['Neural Patient Ingest', 'Synthesized Image Buffer', 'AI Diagnostic Verification'],
  },
  {
    id: 'ai_academy',
    status: 'New!',
    icon: '🏛️',
    title: 'AI Tactical Academy',
    description: 'Generate on-demand high-fidelity lectures on any ultrasound physics concept. Features neural-audio briefings and structured conceptual extraction.',
    features: ['Procedural Briefing Generation', 'Mission Briefing Audio', 'Deep Dive Signal Extraction'],
  },
   {
    id: 'processing',
    status: 'Premium',
    icon: '⚙️',
    title: 'Preprocessing vs. Postprocessing',
    description: 'Understand the critical difference between manipulating live data (preprocessing) and stored data (postprocessing) with this interactive console.',
    features: [
      'Interactive Freeze Buffer',
      'Live Signal Chain Controls',
      'Destructive vs Reversible Data'
    ],
  },
  {
    id: 'tgc',
    status: 'Premium',
    icon: '🎚️',
    title: 'Time Gain Compensation (TGC)',
    description: 'A deep dive into TGC. Learn how we compensate for attenuation, ensures uniform image brightness, and improves diagnostic accuracy through an interactive simulation.',
    features: [
      'Gain Channel Stack Control',
      'Depth Compensation Mapping',
      'Signal Uniformity Calibration'
    ],
  },
  {
    id: 'dynamic_range',
    status: 'Premium',
    icon: '📊',
    title: 'Dynamic Range & Compression',
    description: 'Learn how adjusting the dynamic range affects contrast resolution. This interactive demo shows how to display a wider or narrower range of gray shades.',
    features: [
      'Compression Intensity Slider',
      'Gray Scale Contrast Lab',
      'Signal Map Decibel Control'
    ],
  },
  {
    id: 'qa',
    status: 'Professional',
    icon: '✅',
    title: 'Quality Assurance',
    description: 'Master QA procedures with step-by-step equipment testing protocols and measurement technique guides.',
    features: ['Registration Accuracy Phantom', 'Resolution Target Sweep', 'System Uniformity Audit'],
  },
  {
    id: 'study_guide',
    status: 'Resource',
    icon: '📖',
    title: 'SPI Study Guide & Glossary',
    description: 'A comprehensive study guide covering all core concepts of ultrasound physics, plus an interactive quiz and a detailed glossary of key terms.',
    features: ['Intelligence Database', 'Memory Node Training', 'Rapid Assessment Portal'],
  },
  {
    id: 'jeopardy',
    status: 'Game',
    icon: '🕹️',
    title: 'SPI Jeopardy Challenge',
    description: 'Test your knowledge across core ultrasound physics topics in a fun, competitive Jeopardy-style game. Features 5 categories and 50 questions.',
    features: ['Retrieval Grid Difficulty', 'Sector Sync Scoring', 'Diagnostic Target HUD'],
  },
  {
    id: 'spi_mock_exam',
    status: 'Challenge',
    icon: '⏱️',
    title: 'SPI Mock Exam',
    description: 'A realistic, full-length mock exam to test your knowledge under pressure. Built to simulate the official Sonography Principles & Instrumentation exam.',
    features: ['Full Examination Sync', 'Temporal Pressure Lab', 'Neural Performance Review'],
  },
  {
    id: 'ai_history',
    status: 'Resource',
    icon: '💾',
    title: 'AI Content History',
    description: 'A log of all content generated by EchoBot and other AI features. All generated study plans, flashcards, and feedback are automatically saved here for your review.',
    features: ['Buffer Archive Saving', 'Chronological Uplink Log', 'Historical Data Retrieval'],
  },
];
