
import React from 'react';
import { useAIHistory } from '../../contexts/AIHistoryContext';
import { AIHistoryItem, AIHistoryItemType } from '../../types';
import DemoSection from './DemoSection';
import ControlButton from './ControlButton';

const HistoryItemCard: React.FC<{ item: AIHistoryItem }> = ({ item }) => {
    const renderContent = () => {
        switch (item.type) {
            case 'studyPath':
                return <pre className="text-xs whitespace-pre-wrap bg-black/30 p-2 rounded">{JSON.stringify(item.content, null, 2)}</pre>;
            case 'clinicalImage':
                return <img src={item.content} alt="Generated clinical case" className="rounded-lg max-w-full h-auto" />;
            case 'chat':
                return <p className="italic whitespace-pre-wrap">"{item.content}"</p>;
            default:
                if (typeof item.content === 'string') {
                    return <p className="whitespace-pre-wrap">{item.content}</p>;
                }
                return <pre className="text-xs whitespace-pre-wrap bg-black/30 p-2 rounded">{JSON.stringify(item.content, null, 2)}</pre>;
        }
    };

    // Fix: Added missing aiLecture property to comply with AIHistoryItemType Record
    const typeLabels: Record<AIHistoryItemType, { label: string, icon: string }> = {
        studyPath: { label: 'Study Path', icon: '🗺️' },
        flashcards: { label: 'Flashcards', icon: '🃏' },
        chat: { label: 'Chat Message', icon: '💬' },
        essayQuestion: { label: 'Essay Question', icon: '✍️' },
        definition: { label: 'Definition', icon: '📖' },
        simplification: { label: 'Simplification', icon: '💡' },
        examReview: { label: 'Exam Review', icon: '📊' },
        clinicalImage: { label: 'Clinical Image', icon: '🖼️' },
        clinicalFeedback: { label: 'Case Feedback', icon: '🧑‍⚕️' },
        aiLecture: { label: 'AI Tactical Lecture', icon: '🏛️' },
    };

    return (
        <div className="bg-white/5 p-4 rounded-lg border border-white/10">
            <div className="flex justify-between items-center mb-3">
                <div className="flex items-center gap-2">
                    <span className="text-lg">{typeLabels[item.type].icon}</span>
                    <span className="font-bold text-yellow-400">{typeLabels[item.type].label}</span>
                </div>
                <span className="text-xs text-white/50">{new Date(item.timestamp).toLocaleString()}</span>
            </div>
            {item.context && <p className="text-sm text-white/70 italic mb-2">Context: {item.context}</p>}
            <div className="text-white/90 text-sm">{renderContent()}</div>
        </div>
    );
};

const AIHistoryDemo: React.FC = () => {
    const { history, clearHistory } = useAIHistory();

    return (
        <DemoSection
            title="AI Content History"
            description="All content generated by EchoBot and other AI features is automatically saved here for your review."
        >
            <div className="text-right mb-4">
                <ControlButton onClick={clearHistory} secondary disabled={history.length === 0}>
                    Clear History
                </ControlButton>
            </div>
            <div className="space-y-4 max-h-[70vh] overflow-y-auto pr-2">
                {history.length > 0 ? (
                    history.map(item => <HistoryItemCard key={item.id} item={item} />)
                ) : (
                    <p className="text-center text-white/60 py-8">No AI-generated content has been saved yet.</p>
                )}
            </div>
        </DemoSection>
    );
};

export default AIHistoryDemo;
